/*
LEEWAY HEADER — DO NOT REMOVE

REGION: AI
TAG: CORE.SDK.AGENTLEESDATABASEHUB.MAIN

COLOR_ONION_HEX:
NEON=#39FF14
FLUO=#0DFF94
PASTEL=#C7FFD8

ICON_ASCII:
family=lucide
glyph=file

5WH:
WHAT = AgentLeesDatabaseHub module
WHY = Part of AI region
WHO = LEEWAY Align Agent
WHERE = agents\Web-Agents\AgentLeesDatabaseHub.tsx
WHEN = 2026
HOW = Auto-aligned by LEEWAY align-agent

AGENTS:
ASSESS
ALIGN
AUDIT

LICENSE:
MIT
*/

/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * LEEWAY HEADER
 *
 * TAG: UI.PUBLIC.PAGE.AGENT_DATABASE_HUB.MAIN
 * REGION: 🔵 UI
 *
 * DISCOVERY_PIPELINE:
 *   Voice → Intent → Location → Vertical → Ranking → Render
 *
 * This file implements a multi‑database hub for Agent Lee's "Memory Lake".
 * It exposes unified connectors for several back‑end data stores, including
 * IndexedDB (for low‑latency caching), a browser‑based SQLite engine via
 * sql.js, a WebAssembly version of DuckDB for analytical workloads and
 * sample hooks for remote relational databases and vector stores.  The
 * component renders a dashboard summarising connection status and basic
 * metrics for each data source and exposes a simple query panel that
 * allows the agent to issue SQL commands directly from within the UI.
 *
 * Because DuckDB has been compiled to WebAssembly and runs in any modern
 * browser with a layered API, it can be loaded dynamically at runtime
 * without native dependencies【874286236594197†L463-L470】.  Similarly, sql.js
 * provides an in‑browser SQLite engine but stores data only in memory; if
 * persistence is needed then the database must be manually serialised into
 * IndexedDB because localStorage cannot store binary data and is limited
 * to a few megabytes【261891055882733†L55-L78】.  This module reflects those
 * constraints by wiring the SQL.js connector to an IndexedDB cache so that
 * query results can be stored and later retrieved without re‑execution.
 */

import React, { useEffect, useState, useMemo, useCallback } from 'react';
import { openDB, IDBPDatabase, DBSchema } from 'idb';
import MemoryLake from '../components/MemoryLake';

// -----------------------------------------------------------------------------
// 1. Type Definitions
//
// These definitions describe a generic interface for different database
// connectors.  Each connector exposes a name, human‑readable type and a
// status flag along with asynchronous methods to establish a connection,
// execute arbitrary SQL queries, insert data and return basic metadata.  In
// keeping with the goals of this project the interface is intentionally
// generic so that new backends can be plugged in without modifying the
// surrounding UI.

export type DbStatus = 'disconnected' | 'connecting' | 'connected' | 'error';

export interface QueryResult {
  columns: string[];
  rows: any[][];
}

export interface IDatabaseConnector {
  /** Unique identifier for the database instance. */
  id: string;
  /** Human‑readable name for display in the UI. */
  name: string;
  /** Short type description (e.g. "IndexedDB", "SQL.js", "DuckDB"). */
  type: string;
  /** Current connection state. */
  status: DbStatus;
  /** Optional error message if `status` is set to "error". */
  error?: any;
  /** Establish a connection and populate internal caches. */
  connect: () => Promise<void>;
  /** Execute an SQL statement and return a tabular result. */
  query: (sql: string) => Promise<QueryResult>;
  /** Insert or update data into a table.  Accepts arbitrary JSON values. */
  insert: (table: string, data: any) => Promise<void>;
  /** Return high‑level statistics such as number of tables and approximate size. */
  meta: () => Promise<{ tables: number; rows: number; sizeMB: number }>;
}

// -----------------------------------------------------------------------------
// 2. IndexedDB Cache Connector
//
// This connector implements a simple key‑value store using IndexedDB.  It
// primarily serves as a persistent cache for query results and other
// transient data generated by the agent.  Because IndexedDB stores objects
// natively and supports large quotas, it is ideal for storing serialised
// representations of query results or small blobs without incurring the
// limitations of localStorage【261891055882733†L55-L78】.

interface CacheDB extends DBSchema {
  queries: {
    key: string;
    value: any;
  };
}

class IndexedDbConnector implements IDatabaseConnector {
  id = 'indexedDb';
  name = 'IndexedDB Cache';
  type = 'IndexedDB';
  status: DbStatus = 'disconnected';
  private dbPromise!: Promise<IDBPDatabase<CacheDB>>;
  error?: any;

  async connect() {
    this.status = 'connecting';
    try {
      this.dbPromise = openDB<CacheDB>('agent-lee-cache', 1, {
        upgrade(db) {
          if (!db.objectStoreNames.contains('queries')) {
            db.createObjectStore('queries');
          }
        },
      });
      await this.dbPromise;
      this.status = 'connected';
    } catch (e) {
      this.status = 'error';
      this.error = e;
    }
  }

  /**
   * Execute a pseudo‑SQL query against the cache.  Because IndexedDB
   * doesn't support SQL natively, this method accepts limited commands of
   * the form "SELECT * FROM queries WHERE key = '...';" to retrieve a
   * previously cached result.  Any other statement returns an empty result.
   */
  async query(sql: string): Promise<QueryResult> {
    const db = await this.dbPromise;
    const trimmed = sql.trim().toLowerCase();
    const match = /select\s+\*\s+from\s+queries\s+where\s+key\s*=\s*['"]([^'"]+)['"]/.exec(trimmed);
    if (match) {
      const key = match[1];
      const val = await db.get('queries', key);
      if (val !== undefined) {
        return { columns: ['result'], rows: [[val]] };
      }
    }
    // Return empty when no pattern matched
    return { columns: [], rows: [] };
  }

  /** Store an arbitrary JSON value under the provided table/key.  We treat
   * the table name as the key for simplicity; more sophisticated schemas
   * can be layered on top if needed. */
  async insert(table: string, data: any): Promise<void> {
    const db = await this.dbPromise;
    await db.put('queries', data, table);
  }

  async meta(): Promise<{ tables: number; rows: number; sizeMB: number }> {
    const db = await this.dbPromise;
    let count = 0;
    let bytes = 0;
    const tx = db.transaction('queries');
    const store = tx.store;
    for await (const cursor of store) {
      count++;
      const value = cursor.value;
      bytes += JSON.stringify(value).length;
    }
    return { tables: 1, rows: count, sizeMB: bytes / 1024 / 1024 };
  }
}

// -----------------------------------------------------------------------------
// 3. SQL.js Connector
//
// sql.js compiles SQLite to WebAssembly so that it runs entirely within the
// browser.  The library provides a familiar SQL interface but, by default,
// keeps the entire database in memory.  To persist the state across
// sessions the database must be serialised and saved into a persistent store
// such as IndexedDB【261891055882733†L55-L78】.  This connector encapsulates
// those details and exposes a unified query API.

interface SqlJsModule {
  Database: any;
  FS: any;
  ccall: any;
  ERRNO_CODES: any;
}

class SqlJsConnector implements IDatabaseConnector {
  id = 'sqlJs';
  name = 'SQLite (sql.js)';
  type = 'SQL.js';
  status: DbStatus = 'disconnected';
  error?: any;
  private SQL: SqlJsModule | null = null;
  private db: any = null;
  private cache: IndexedDbConnector;

  constructor(cache: IndexedDbConnector) {
    this.cache = cache;
  }

  async connect() {
    this.status = 'connecting';
    try {
      // Dynamically import the sql.js library.  We locate the WASM file on
      // a CDN so that bundlers do not need to embed it.  If this import
      // fails the connection will remain in the "error" state.
      // @ts-ignore
      const initSqlJs = (await import('https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.8.0/sql-wasm.js')).default;
      const SQL = await initSqlJs({
        locateFile: (file: string) => `https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.8.0/${file}`,
      });
      this.SQL = SQL;
      this.db = new SQL.Database();
      this.status = 'connected';
    } catch (e) {
      this.status = 'error';
      this.error = e;
    }
  }

  async query(sql: string): Promise<QueryResult> {
    if (!this.db) {
      throw new Error('SQL.js database is not initialised');
    }
    const trimmed = sql.trim().toLowerCase();
    // If the statement is a SELECT we attempt to look up a cached result
    // first.  Otherwise we execute it directly.
    if (trimmed.startsWith('select')) {
      const cacheKey = `sqljs:${sql}`;
      const cached = await this.cache.query(`SELECT * FROM queries WHERE key = '${cacheKey}'`);
      if (cached.rows.length > 0) {
        const [result] = cached.rows[0];
        return result as QueryResult;
      }
    }
    try {
      const result = this.db.exec(sql);
      if (result.length === 0) {
        return { columns: [], rows: [] };
      }
      const res = result[0];
      const queryResult: QueryResult = { columns: res.columns, rows: res.values };
      // Persist the result into the cache for future lookups
      if (trimmed.startsWith('select')) {
        const cacheKey = `sqljs:${sql}`;
        await this.cache.insert(cacheKey, queryResult);
      }
      return queryResult;
    } catch (e) {
      throw e;
    }
  }

  async insert(table: string, data: any): Promise<void> {
    if (!this.db) throw new Error('SQL.js database is not initialised');
    // Naively create a table if it does not exist.  Keys of the data object
    // define column names and values are inserted directly.  Note that this
    // does not handle types or escaping and is intended solely as a simple
    // demonstration.
    const cols = Object.keys(data);
    const vals = Object.values(data);
    const colDefs = cols.map((c) => `${c} TEXT`).join(', ');
    const placeholders = vals.map(() => '?').join(', ');
    this.db.exec(`CREATE TABLE IF NOT EXISTS ${table} (${colDefs});`);
    const stmt = this.db.prepare(`INSERT INTO ${table} (${cols.join(', ')}) VALUES (${placeholders});`);
    stmt.run(...vals);
    stmt.free();
  }

  async meta(): Promise<{ tables: number; rows: number; sizeMB: number }> {
    if (!this.db) throw new Error('SQL.js database is not initialised');
    // Query sqlite_master to count tables
    const tableResult = this.db.exec(`SELECT COUNT(*) AS count FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';`);
    const tables = tableResult?.[0]?.values?.[0]?.[0] ?? 0;
    // Estimate rows as the sum of row counts from all tables
    let rows = 0;
    const tablesList = this.db.exec(`SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';`);
    for (const entry of tablesList?.[0]?.values ?? []) {
      const tableName = entry[0];
      const countRes = this.db.exec(`SELECT COUNT(*) AS c FROM ${tableName};`);
      rows += countRes?.[0]?.values?.[0]?.[0] ?? 0;
    }
    // Serialise database to determine size
    const binary = this.db.export();
    const sizeMB = binary.length / 1024 / 1024;
    return { tables, rows, sizeMB };
  }
}

// -----------------------------------------------------------------------------
// 4. DuckDB (WASM) Connector
//
// DuckDB is a fast analytical database.  When compiled to WebAssembly it can
// run in the browser with no native dependencies【874286236594197†L463-L470】.
// Because the library isn't bundled with this project, we load it via a
// dynamic import from a CDN.  This connector initialises the DuckDB engine
// asynchronously and exposes the same query API as other connectors.

class DuckDbConnector implements IDatabaseConnector {
  id = 'duckDb';
  name = 'DuckDB (WASM)';
  type = 'DuckDB';
  status: DbStatus = 'disconnected';
  error?: any;
  private db: any;
  private worker: any;

  async connect() {
    this.status = 'connecting';
    try {
      // Dynamically import duckdb-wasm from the jsDelivr CDN.  The +esm
      // suffix returns an ES module that can be imported natively.  See
      // https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm/+esm for details.
      // @ts-ignore
      const duckdb = await import('https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.25.1/+esm');
      // Select a bundle that contains both the main module and a worker.
      const bundles = duckdb.getJsDelivrBundles();
      // Choose the first bundle; in practice you might prefer the mvp or eh bundle.
      const bundle = bundles[0];
      // Create a new asynchronous worker.  This runs queries off the main thread.
      const worker = new duckdb.AsyncDuckDBWorker();
      const db = new duckdb.DuckDB(worker);
      await db.instantiate(bundle.mainModule, bundle.pthreadWorker);
      // Open an in‑memory database; persistent storage would require OPFS.
      const conn = await db.connect();
      this.worker = worker;
      this.db = conn;
      this.status = 'connected';
    } catch (e) {
      this.status = 'error';
      this.error = e;
    }
  }

  async query(sql: string): Promise<QueryResult> {
    if (!this.db) throw new Error('DuckDB database not initialised');
    const result = await this.db.query(sql);
    return { columns: result.columns, rows: result.toArray() };
  }

  async insert(table: string, data: any): Promise<void> {
    if (!this.db) throw new Error('DuckDB database not initialised');
    // Create table if it doesn't exist
    const cols = Object.keys(data);
    const colDefs = cols.map((c) => `${c} TEXT`).join(', ');
    await this.db.query(`CREATE TABLE IF NOT EXISTS ${table} (${colDefs});`);
    const values = cols.map((c) => `'${String(data[c]).replace(/'/g, "''")}'`).join(', ');
    await this.db.query(`INSERT INTO ${table} (${cols.join(', ')}) VALUES (${values});`);
  }

  async meta(): Promise<{ tables: number; rows: number; sizeMB: number }> {
    if (!this.db) throw new Error('DuckDB database not initialised');
    const res = await this.db.query(`SELECT COUNT(*) AS count FROM information_schema.tables WHERE table_schema='main';`);
    const tables = res.get(0).get('count');
    const res2 = await this.db.query(`SELECT SUM(reltuples) AS rows FROM pg_catalog.pg_class WHERE relname IN (SELECT table_name FROM information_schema.tables WHERE table_schema='main');`);
    const rows = res2.get(0).get('rows') ?? 0;
    // DuckDB doesn't expose file size for in‑memory DB; we report 0
    return { tables, rows, sizeMB: 0 };
  }
}

// -----------------------------------------------------------------------------
// 5. Remote DB Connector (Stub)
//
// Many relational databases such as PostgreSQL or MySQL are not accessible
// directly from the browser due to cross‑origin restrictions and the need
// for authentication.  This connector provides a placeholder illustrating
// how one might bridge to a server‑side API that executes queries on the
// user's behalf.  In order to work fully the agent would need to supply
// appropriate connection strings and implement an API endpoint to relay
// queries.  Here we assume there exists an endpoint at /api/db/query.

class RemoteDbConnector implements IDatabaseConnector {
  id: string;
  name: string;
  type: string;
  status: DbStatus = 'disconnected';
  error?: any;
  private endpoint: string;

  constructor(id: string, name: string, type: string, endpoint: string) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.endpoint = endpoint;
  }

  async connect() {
    // For remote connectors we assume connectivity is always available and
    // mark the status as connected.  In a real implementation this could
    // perform a health check against the endpoint.
    this.status = 'connected';
  }

  async query(sql: string): Promise<QueryResult> {
    try {
      const res = await fetch(this.endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query: sql }),
      });
      if (!res.ok) throw new Error(`Remote DB error: ${res.statusText}`);
      const json = await res.json();
      return json as QueryResult;
    } catch (e) {
      this.status = 'error';
      this.error = e;
      throw e;
    }
  }

  async insert(table: string, data: any): Promise<void> {
    await this.query(`INSERT INTO ${table} (${Object.keys(data).join(', ')}) VALUES (${Object.values(data).map((v) => `'${v}'`).join(', ')});`);
  }

  async meta(): Promise<{ tables: number; rows: number; sizeMB: number }> {
    // Endpoint must implement a metadata route; we return placeholder values
    return { tables: 0, rows: 0, sizeMB: 0 };
  }
}

// -----------------------------------------------------------------------------
// 6. Vector Store Connector (Stub)
//
// Vector databases store high‑dimensional vectors for similarity search and
// retrieval augmented generation.  Implementing a full vector database in
// browser would be out of scope here, but this stub demonstrates the API.

class VectorDbConnector implements IDatabaseConnector {
  id = 'vectorDb';
  name = 'Vector Store';
  type = 'VectorDB';
  status: DbStatus = 'connected';
  error?: any;
  private store: Record<string, number[]> = {};

  async connect() {
    // In this stub there is nothing to initialise.
    this.status = 'connected';
  }

  async query(sql: string): Promise<QueryResult> {
    // We interpret the SQL as a similarity search when it matches the
    // pattern SELECT id, similarity FROM vectors WHERE MATCH('...')
    const match = /match\s*\(\s*['"]([^'"]+)['"]\s*\)/i.exec(sql);
    if (match) {
      const vectorString = match[1];
      const queryVector = vectorString.split(',').map((v) => parseFloat(v));
      const results: [string, number][] = [];
      for (const [id, vec] of Object.entries(this.store)) {
        // Compute cosine similarity
        let dot = 0;
        let normA = 0;
        let normB = 0;
        for (let i = 0; i < vec.length; i++) {
          dot += vec[i] * queryVector[i];
          normA += vec[i] ** 2;
          normB += queryVector[i] ** 2;
        }
        const sim = dot / (Math.sqrt(normA) * Math.sqrt(normB));
        results.push([id, sim]);
      }
      // Sort by similarity descending
      results.sort((a, b) => b[1] - a[1]);
      return { columns: ['id', 'similarity'], rows: results };
    }
    return { columns: [], rows: [] };
  }

  async insert(table: string, data: any): Promise<void> {
    // Expect data = { id: string, vector: number[] }
    this.store[data.id] = data.vector;
  }

  async meta(): Promise<{ tables: number; rows: number; sizeMB: number }> {
    const count = Object.keys(this.store).length;
    // Roughly estimate size as (vector length * 8 bytes) per entry
    let totalDims = 0;
    for (const vec of Object.values(this.store)) {
      totalDims += vec.length;
    }
    const sizeMB = (totalDims * 8) / 1024 / 1024;
    return { tables: 1, rows: count, sizeMB };
  }
}

// -----------------------------------------------------------------------------
// 7. Dashboard Component
//
// The core React component renders a high‑level overview of all database
// connectors and a simple query editor.  Upon mount it initialises all
// connectors in parallel, displays their status and metrics and allows the
// agent to select a database, run a query and inspect results.  At the
// bottom of the page the existing MemoryLake component is embedded to
// provide continuity with the rest of the agent's architecture.

const AgentLeesDatabaseHub: React.FC = () => {
  // Instantiate the cache first so that the SQL.js connector can persist
  const [cacheConnector] = useState(() => new IndexedDbConnector());
  const [connectors, setConnectors] = useState<IDatabaseConnector[]>([]);
  const [selected, setSelected] = useState<IDatabaseConnector | null>(null);
  const [queryText, setQueryText] = useState('');
  const [result, setResult] = useState<QueryResult | null>(null);
  const [loading, setLoading] = useState(false);

  // Build connector list on first render
  useEffect(() => {
    const sqlJs = new SqlJsConnector(cacheConnector);
    const duck = new DuckDbConnector();
    const remote = new RemoteDbConnector('remote', 'Server DB', 'PostgreSQL', '/api/db/query');
    const vector = new VectorDbConnector();
    setConnectors([cacheConnector, sqlJs, duck, remote, vector]);
    // Automatically select the first connector once they are initialised
    setSelected(cacheConnector);
  }, [cacheConnector]);

  // Connect all databases when the connector list changes
  useEffect(() => {
    connectors.forEach((c) => {
      if (c.status === 'disconnected') {
        c.connect().catch(() => {});
      }
    });
  }, [connectors]);

  // Run the query against the selected database
  const runQuery = useCallback(async () => {
    if (!selected) return;
    setLoading(true);
    try {
      const res = await selected.query(queryText);
      setResult(res);
    } catch (e) {
      // capture error in result so it can be displayed in the UI
      setResult({ columns: ['error'], rows: [[String(e)]] });
    } finally {
      setLoading(false);
    }
  }, [selected, queryText]);

  // Compute metrics for each connector using SWR‑like pattern
  const [metrics, setMetrics] = useState<Record<string, { tables: number; rows: number; sizeMB: number }> | null>(null);
  useEffect(() => {
    const fetchMetrics = async () => {
      const m: Record<string, { tables: number; rows: number; sizeMB: number }> = {};
      await Promise.all(connectors.map(async (c) => {
        try {
          const meta = await c.meta();
          m[c.id] = meta;
        } catch {
          m[c.id] = { tables: 0, rows: 0, sizeMB: 0 };
        }
      }));
      setMetrics(m);
    };
    fetchMetrics();
  }, [connectors]);

  return (
    <div style={{ fontFamily: 'Outfit, sans-serif', color: '#eee', padding: '1rem', backgroundColor: '#030410', minHeight: '100vh' }}>
      <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
        <div style={{ display: 'flex', alignItems: 'center' }}>
          <div style={{ fontSize: '1.5rem', fontWeight: 700, marginRight: '0.5rem' }}>Agent Lee's DB Hub</div>
        </div>
        <div style={{ display: 'flex', gap: '1rem' }}>
          {connectors.map((c) => (
            <div key={c.id} style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end' }}>
              <span style={{ fontSize: '0.8rem', opacity: 0.7 }}>{c.name}</span>
              <span style={{ fontSize: '0.8rem' }}>
                {c.status === 'connected' && metrics && metrics[c.id]
                  ? `${metrics[c.id].tables} tables, ${metrics[c.id].rows} rows`
                  : c.status === 'connecting'
                  ? 'Connecting...'
                  : c.status === 'error'
                  ? 'Error'
                  : '—'}
              </span>
            </div>
          ))}
        </div>
      </header>
      <main style={{ display: 'grid', gridTemplateColumns: '250px 1fr', gap: '1rem' }}>
        <aside style={{ background: 'rgba(12, 15, 35, 0.7)', padding: '1rem', borderRadius: '8px' }}>
          <h3 style={{ marginBottom: '0.5rem', fontSize: '1rem', borderBottom: '1px solid #444', paddingBottom: '0.5rem' }}>Databases</h3>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
            {connectors.map((c) => (
              <li key={c.id} onClick={() => setSelected(c)} style={{
                padding: '0.5rem 0.25rem',
                cursor: 'pointer',
                background: selected?.id === c.id ? 'rgba(108, 71, 255, 0.2)' : 'transparent',
                borderRadius: '6px',
              }}>
                <div style={{ fontWeight: 500 }}>{c.name}</div>
                <div style={{ fontSize: '0.7rem', opacity: 0.7 }}>{c.type}</div>
              </li>
            ))}
          </ul>
        </aside>
        <section style={{ background: 'rgba(12, 15, 35, 0.7)', padding: '1rem', borderRadius: '8px', display: 'flex', flexDirection: 'column', minHeight: '400px' }}>
          <h3 style={{ marginBottom: '0.5rem', fontSize: '1rem', borderBottom: '1px solid #444', paddingBottom: '0.5rem' }}>Query Editor</h3>
          <textarea
            value={queryText}
            onChange={(e) => setQueryText(e.target.value)}
            rows={5}
            placeholder={selected ? `Enter SQL for ${selected.name}...` : 'Select a database'}
            style={{ width: '100%', padding: '0.5rem', borderRadius: '4px', background: '#1a1d3a', color: '#eee', border: '1px solid #444', marginBottom: '0.5rem', fontFamily: 'monospace' }}
          />
          <button
            disabled={!selected || loading}
            onClick={runQuery}
            style={{
              padding: '0.5rem 1rem',
              borderRadius: '4px',
              background: selected ? '#6C47FF' : '#444',
              color: '#fff',
              border: 'none',
              cursor: selected ? 'pointer' : 'not-allowed',
              alignSelf: 'flex-start',
              marginBottom: '1rem',
            }}
          >
            {loading ? 'Running...' : 'Run Query'}
          </button>
          {result && (
            <div style={{ overflowX: 'auto' }}>
              {result.columns.length === 0 ? (
                <div style={{ opacity: 0.7 }}>No results</div>
              ) : (
                <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8rem' }}>
                  <thead>
                    <tr>
                      {result.columns.map((col) => (
                        <th key={col} style={{ textAlign: 'left', padding: '4px', borderBottom: '1px solid #444' }}>{col}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {result.rows.map((row, i) => (
                      <tr key={i}>
                        {row.map((cell, j) => (
                          <td key={j} style={{ padding: '4px', borderBottom: '1px solid #333', verticalAlign: 'top' }}>{String(cell)}</td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          )}
        </section>
      </main>
      <section style={{ marginTop: '2rem' }}>
        <h3 style={{ marginBottom: '0.5rem', fontSize: '1rem', borderBottom: '1px solid #444', paddingBottom: '0.5rem' }}>Memory Lake</h3>
        {/* Render the MemoryLake component to allow interaction with neural storage */}
        <div style={{ background: 'rgba(12, 15, 35, 0.7)', borderRadius: '8px', padding: '1rem' }}>
          <MemoryLake />
        </div>
      </section>
    </div>
  );
};

export default AgentLeesDatabaseHub;